create database lista002;
use lista002;
CREATE TABLE alunos (codigo int, nome varchar(50), telefone varchar(50), cidade varchar(50));
desc alunos;
CREATE TABLE alunos2 (codigo int, nome varchar(200), telefone varchar(50), cidade varchar(100));
create table funcionários (nome varchar(200), endereço varchar(200), telefone varchar(50) , cidade varchar(100), estado varchar(50), cep char(8), rg char(9), cpf varchar(11), salário float);
desc funcionários;
create table fornecedores (nome varchar(200), endereço varchar(200), telefone varchar(50) , cidade varchar(100), estado varchar(50), cep char(8), cnpj char(14), email varchar(100));
desc fornecedores;
create table livros (código varchar(100), nome varchar(200), categoria varchar(50) , resumo varchar(2000), precocusto float, precovenda float);
desc livros;
create table estoque (código varchar(100), nomedoproduto varchar(200), categoria varchar(50) , quantidade int, fornecedor varchar(200));
desc estoque;
create table notas (código varchar(100), nomedoaluno varchar(200), bimestre int);
desc notas;
create table caixa (código varchar(100), dia datetime, descrição varchar(150), débito varchar(100), crédito varchar(100));
desc caixa;
create table contasAPagar (código varchar(100), data_conta datetime, descrição varchar(150), valor float, data_recebimento datetime);
desc contasAPagar;
create table contasAReceber (código varchar(100), data_conta datetime, descrição varchar(150), valor float, data_recebimento datetime);
desc contasAReceber;
create table filmes (código varchar(100), nome varchar(200), categoria varchar(50) , sinopse varchar(2000), diretor varchar(200));
desc filmes;
create table CDs (código varchar(100), nome varchar(200), cantor varchar(200), ano int, quantidadedemusicas int);
desc CDs;
DROP TABLE alunos2;
desc alunos2;
DROP TABLE livros;
DROP TABLE contasAPagar;
DROP TABLE contasAReceber;
DROP TABLE filmes;
desc livros;
desc contasAPagar;
desc contasAReceber;
desc filmes;
alter table alunos rename to super_alunos;
desc super_alunos;
alter table estoque rename to produtos;
alter table notas rename to aprovados;
alter table aprovados rename to notas;
drop table dinheiro;
drop table notas;
alter table super_alunos rename to alunos;
alter table alunos rename to estudantes;
alter table estudantes rename to super_estudantes;
drop table super_estudantes;
desc super_alunos;
desc alunos;
ALTER TABLE ALUNOS ADD ESTADO VARCHAR;
create table caixa;
alter table caixa add observação varchar(20);
alter table caixa add cpf varchar(11);
desc caixa;
alter table caixa add saldo float;


